---
id: rubykaigi2016
base_name: slide
tags:
- rubykaigi2016
presentation_date: 2016-09-08
version: 1.0.0
licenses:
- CC BY-SA 4.0
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: 
  name: okkez
  email: okkez000@gmail.com
  rubygems_user: okkez
  slideshare_user: okkez
  speaker_deck_user: okkez
